# OtterWiki Tailscale Ingress
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: otterwiki
  namespace: wiki
spec:
  ingressClassName: tailscale
  tls:
    - hosts:
        - otterwiki
  defaultBackend:
    service:
      name: otterwiki
      port:
        number: 80

# OtterWiki Service
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: otterwiki
  name: otterwiki
  namespace: wiki
spec:
  ports:
  - name: otterwiki
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: otterwiki
  type: ClusterIP

# OtterWiki Volume
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: otterwiki-database
  namespace: wiki
  labels:
    backup: "true"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path

# OtterWiki Deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otterwiki
  namespace: wiki
spec:
  replicas: 1
  minReadySeconds: 1
  selector:
    matchLabels:
      app: otterwiki
  template:
    metadata:
      labels:
        app: otterwiki
    spec:
      terminationGracePeriodSeconds: 1
      containers:
      - name: otterwiki
        image: redimp/otterwiki:latest
        env:
        - name: READ_ACCESS
          value: REGISTERED
        - name: WRITE_ACCESS
          value: REGISTERED
        - name: ATTACHMENT_ACCESS
          value: REGISTERED
        - name: DISABLE_REGISTRATION
          value: "True"
        volumeMounts:
        - name: database
          mountPath: /app-data
      volumes:
      - name: database
        persistentVolumeClaim:
          claimName: otterwiki-database